spring:
  push:
    vapid:
      public-key: ${VAPID_PUBLIC_KEY}
      private-key: ${VAPID_PRIVATE_KEY}
      subject: ${VAPID_SUBJECT}
  application:
    name: nasa-openapi-svc
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        default_schema: NasaDB
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    locations: classpath:/db/migration
    schemas: NasaDB
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      schema: NasaDB
logging:
  level:
    root: WARN
    org.hibernate.SQL: ERROR
