CREATE TABLE "NasaDB"."PushSubscription" (
    ID SERIAL PRIMARY KEY,
    SUBSCRIBER VARCHAR(50),
    ENDPOINT VARCHAR(255) NOT NULL,
    PUBLIC_KEY VARCHAR(100) NOT NULL,
    AUTH_SECRET VARCHAR(32) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT UNIQUE_ENDPOINT UNIQUE (ENDPOINT)
);

ALTER INDEX "NasaDB"."idx_ublished_date" RENAME TO "IDX_PUBLISHED_DATE";