CREATE TABLE "NasaDB"."PicOfDay" (
    ID SERIAL PRIMARY KEY,
    COPYRIGHT VARCHAR(255),
    PUBLISHED_DATE DATE NOT NULL,
    EXPLANATION VARCHAR(2048),
    MEDIATYPE VARCHAR(32) NOT NULL,
    TITLE VARCHAR(128) NOT NULL,
    URL VARCHAR(128) NOT NULL
);
